theme: jekyll-theme-slate
title: Solaar
description: Linux Device manager for the Logitech Unifying Receiver.
tagline: Linux Device manager for the Logitech Unifying Receiver.
owner: pwr
owner_url: https://github.com/pwr
repository: https://github.com/pwr/Solaar
version: 0.9.2
ga_id: UA-36908718-1
show_downloads: true
