title: Solaar
description: Linux Device manager for the Logitech Unifying Receiver.
tagline: Linux Device manager for the Logitech Unifying Receiver.
owner: pwr
owner_url: https://github.com/pwr
repository: pwr/Solaar
version: 0.9.2
ga_id: UA-36908718-1
show_downloads: false
encoding: utf-8
theme: jekyll-theme-slate